# Generated by Django 5.2.7 on 2025-11-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la categoria')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de compra')),
                ('costo_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de venta')),
                ('codigo_barra', models.CharField(max_length=25, verbose_name='Codigo de Barra')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria', verbose_name='Categoria del producto')),
            ],
        ),
    ]
