# Generated by Django 5.2.7 on 2025-12-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de Campaña')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('header_img', models.ImageField(upload_to='catalogos/headers/', verbose_name='Banner Superior')),
                ('footer_img', models.ImageField(upload_to='catalogos/footers/', verbose_name='Banner Inferior')),
                ('fondo_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de Fondo (Hex)')),
                ('productos', models.ManyToManyField(related_name='catalogos', to='productos.producto', verbose_name='Productos a incluir')),
            ],
        ),
    ]
