# Generated by Django 5.2.7 on 2025-11-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del almacén')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación (opcional)')),
            ],
        ),
    ]
