# Generated by Django 5.2.7 on 2025-11-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0002_compra_estado_venta_estado_compraitem_ventaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %'),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
