# Generated by Django 5.2.7 on 2025-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0003_ventaitem_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_comprobante',
            field=models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° Documento'),
        ),
    ]
