# Generated by Django 5.2.7 on 2025-11-06 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del almacén')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación (opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la categoria')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de compra')),
                ('costo_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de venta')),
                ('codigo_barra', models.CharField(max_length=25, verbose_name='Codigo de Barra')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria', verbose_name='Categoria del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha del movimiento')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.almacen', verbose_name='Almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Existencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cantidad del Producto')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventario.almacen', verbose_name='Almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
