# Generated by Django 5.2.7 on 2025-11-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('inventario', '0002_cliente_compra_proveedor_movimiento_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencias',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='almacen.almacen', verbose_name='Almacen'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='almacen.almacen', verbose_name='Almacén'),
        ),
        migrations.DeleteModel(
            name='Almacen',
        ),
    ]
